# ProtTale Environment Configuration
# 
# Installation Instructions:
# 1. Create the environment:
#    conda env create -n ProtTale -f ProtTale_environment.yml
#
# 2. Activate the environment:
#    conda activate ProtTale
#
# 3. Install packages with dependency conflicts:
#   pip install salesforce-lavis==1.0.2 --no-deps
#   SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True pip install opendelta==0.3.2
#
name: ProtTale
channels:
  - pytorch
  - nvidia
  - nvidia/label/cuda-11.7.1
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - atk-1.0=2.36.0=h3371d22_4
  - blas=1.0=openblas
  - brotli-python=1.0.9=py310h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py310h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cryptography=39.0.1=py310h9ce1e76_2
  - cuda-cccl=11.7.91=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.7.99=0
  - cuda-cupti=11.8.87=0
  - cuda-driver-dev=11.7.99=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.7.1=0
  - cuda-nvcc=11.7.99=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.7.99=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.9=3
  - docopt-ng=0.9.0=pyhd8ed1ab_1
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.17.0=py310h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h2c49b7f_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h36c2ea0_0
  - ftpretty=0.4.0=pyhd8ed1ab_1
  - gdk-pixbuf=2.42.10=h5eee18b_1
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.2=h5eee18b_0
  - glib=2.84.2=h6a678d5_0
  - glib-tools=2.84.2=h6a678d5_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - goatools=1.5.2=pyhd8ed1ab_0
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.49.0=h85b4f2f_0
  - gtk2=2.24.33=h90689f9_2
  - gts=0.7.6=h64030ff_2
  - harfbuzz=4.3.0=hf52aaf7_2
  - icu=73.1=h6a678d5_0
  - idna=3.7=py310h06a4308_0
  - jedi=0.19.2=py310h06a4308_0
  - jinja2=3.1.6=py310h06a4308_0
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.10.3.66=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.7.2.91=0
  - libcufile=1.14.1.1=4
  - libcufile-dev=1.3.1.18=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.2.10.91=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.0.1=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.4.91=0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgd=2.3.3=h695aa2c_1
  - libglib=2.84.2=h37c7471_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.7.4.75=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - librsvg=2.54.3=h7abd40a_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=hffd6297_1
  - libtool=2.4.6=h9c3ff4c_1008
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py310h5eee18b_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.4.2=py310h06a4308_0
  - nomkl=3.0=0
  - openh264=2.1.1=h4ff587b_0
  - openpyxl=3.1.5=py310h5eee18b_1
  - openssl=3.0.16=h5eee18b_0
  - pango=1.50.7=hbd2fdc8_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.42=hebb0a14_1
  - pillow=9.4.0=py310h6a678d5_1
  - pip=25.1=pyhc872135_2
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pydot=4.0.1=py310hff52083_1
  - pyopenssl=23.2.0=py310h06a4308_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.18=h1a3bd86_0
  - python_abi=3.10=2_cp310
  - pyyaml=6.0.2=py310h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.4=py310h06a4308_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - statsmodels=0.14.5=py310h76ea63d_0
  - sympy=1.13.3=py310h06a4308_1
  - tk=8.6.14=h993c535_1
  - typing_extensions=4.12.2=py310h06a4308_0
  - urllib3=1.26.19=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xlsxwriter=3.2.6=pyhd8ed1ab_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - bigmodelvis==0.0.1
      - biopython==1.85
      - biotite==0.41.2
      - biotraj==1.2.2
      - bleach==6.2.0
      - blinker==1.9.0
      - blis==0.7.11
      - braceexpand==0.1.7
      - cachetools==6.1.0
      - catalogue==2.0.10
      - cfgv==3.4.0
      - cheroot==10.0.1
      - click==8.2.1
      - cloudpathlib==0.16.0
      - confection==0.1.5
      - contexttimer==0.3.3
      - crcmod==1.7
      - cymem==2.0.11
      - datasets==3.6.0
      - decorator==5.2.1
      - decord==0.6.0
      - deepspeed==0.17.2
      - delta-center-client==0.0.4
      - dill==0.3.8
      - distlib==0.3.9
      - distro==1.9.0
      - einops==0.8.1
      - esm==3.1.1
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fairscale==0.4.4
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - h11==0.16.0
      - hf-xet==1.1.5
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.33.0
      - identify==2.6.12
      - imageio==2.37.0
      - iopath==0.1.10
      - ipython==8.37.0
      - jaraco-functools==4.2.1
      - jiter==0.12.0
      - jmespath==0.10.0
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - kaggle==1.7.4.5
      - langcodes==3.5.0
      - language-data==1.3.0
      - lazy-loader==0.4
      - lightning-utilities==0.14.3
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - more-itertools==10.7.0
      - msgpack==1.1.1
      - msgpack-numpy==0.4.8
      - multidict==6.5.0
      - multiprocess==0.70.16
      - murmurhash==1.0.13
      - narwhals==1.43.1
      - ninja==1.11.1.4
      - nltk==3.9.1
      - nodeenv==1.9.1
      - numpy==1.26.4
      - omegaconf==2.3.0
      - openai==2.7.2
      - opencv-python-headless==4.5.5.64
      - opendatasets==0.1.22
      - oss2==2.15.0
      - packaging==25.0
      - pandas==2.3.0
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.3.8
      - plotly==6.1.2
      - portalocker==3.2.0
      - pre-commit==4.2.0
      - preshed==3.0.10
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==20.0.0
      - pycocoevalcap==1.2
      - pycocotools==2.0.10
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydeck==0.9.1
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - python-magic==0.4.27
      - python-slugify==8.0.4
      - pytorch-lightning==2.5.2
      - pytz==2025.2
      - referencing==0.36.2
      - regex==2024.11.6
      - rich==14.0.0
      - rouge-score==0.1.2
      - rpds-py==0.25.1
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==6.4.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - spacy==3.7.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - stack-data==0.6.3
      - streamlit==1.46.0
      - tenacity==9.1.2
      - text-unidecode==1.3
      - thinc==8.1.12
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==0.4.12
      - tokenizers==0.13.3
      - toml==0.10.2
      - torch==2.2.0
      - torchaudio==2.2.0
      - torchmetrics==1.7.3
      - torchtext==0.17.0
      - torchvision==0.17.0
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.30.0
      - triton==2.2.0
      - typer==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - virtualenv==20.31.2
      - wasabi==1.1.3
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - weasel==0.3.4
      - web-py==0.62
      - webdataset==1.0.2
      - webencodings==0.5.1
      - wrapt==1.17.2
      - xxhash==3.5.0
      - yacs==0.1.8
      - yarl==1.20.1
      - zstd==1.5.7.2
